### ISSUE TITLE
Add an image for Ruby 3.1

### ISSUE THREAD

**Issue by matthewford** [moritzheiber/ruby-jemalloc-docker#1]
If we can update the image for ruby:3.1.2-slim-bullseye, then Mastadon can run on 3.1 https://github.com/mastodon/mastodon/pull/21061

Not entirely sure how to run two versions of the Dockerfile at once for those on 3.0

**Comment by moritzheiber** [comment]
07fcdae397f16dd3279bd368db2a66a3417f9ec5 adds support for this. Once the pipeline has run successfully the image should be available and then I’ll close this issue 😊

**Comment by moritzheiber** [comment]
https://github.com/moritzheiber/ruby-jemalloc-docker/pkgs/container/ruby-jemalloc/51641954?tag=3.1.2-slim

**Comment by matthewford** [comment]
Thanks @moritzheiber
