### ISSUE TITLE
Dockerfile in master does not reflect images on GHCR

### ISSUE THREAD

**Issue by untitaker** [moritzheiber/ruby-jemalloc-docker#5]
ISTM that when #3 was fixed, the Dockerfile was not actually updated. The file in master refers to Ruby 3.0.

**Comment by moritzheiber** [comment]
Ruby `3.0.5` is the default (as mentioned in the README), with the other two Ruby minor versions dynamically passed into the build process, and there are images available for `3.0.5` as well as `3.1.x` and `3.2.x.`

You can either check the GitHub actions process or fetch the corresponding information for building the right image yourself using https://github.com/moritzheiber/ruby-version-checker-rs or the Ruby website (you need to pass `RUBY_VERSION` and `RUBY_CHECKSUM` as build arguments).

You may also use the pre-built images available from the registry.

Either way, this doesn’t sound like a bug to me..?

I will add these instructions to the README though.

**Comment by moritzheiber** [comment]
I've updated the README with appropriate instructions: https://github.com/moritzheiber/ruby-jemalloc-docker/commit/79a459e512e8e20a482ccc814085308afa822b3c

**Comment by untitaker** [comment]
Oh i see thanks. I guess I was just sort of assuming this must have been a missed check-in because I thought, surely there's gotta be some changes to the Dockerfile to get YJIT working. Nevermind then!

**Comment by moritzheiber** [comment]
All good! Glad we got this sorted, and I was able to improve the docs in the process 😊 Thanks!
