### ISSUE TITLE
Ruby 3.2.2 / 3.1.4 / 3.0.6 released.

### ISSUE THREAD

**Issue by shleeable** [moritzheiber/ruby-jemalloc-docker#7]

**Comment by moritzheiber** [comment]
Once https://github.com/moritzheiber/ruby-jemalloc-docker/actions/runs/4572989449 completes these new releases should be available as images. I'll wait with closing this ticket until then :slightly_smiling_face:

**Comment by moritzheiber** [comment]
All of the images are available now :smiley:

**Comment by shleeable** [comment]
Thank you @moritzheiber
