### ISSUE TITLE
Confirming jemalloc is enabled?

### ISSUE THREAD

**Issue by jonbuda** [moritzheiber/ruby-jemalloc-docker#9]
Looking forward to using this Docker build but I'm having a hard time confirming that Ruby is compiled with jemalloc support enabled.

According to everywhere I look, running `ruby -r rbconfig -e "puts RbConfig::CONFIG['LIBS']"` should confirm jemalloc support but I don't see anything, nor does `RbConfig::CONFIG` within IRB output anything related to jemalloc?

using `FROM ghcr.io/moritzheiber/ruby-jemalloc:3.2.2-slim` in my Dockerfile and running as `--platform linux/arm64`

**Comment by moritzheiber** [comment]
Have you tried running `ruby -v --yjit `? It’s [the officially recommended way](https://github.com/ruby/ruby/blob/master/doc/yjit/yjit.md?plain=1#L180) of seeing whether or not a distribution has been configured with YJIT enabled.

**Comment by jonbuda** [comment]
yeah, `--yjit` definitely works fine, but `jemalloc` is a different thing entirely, isn't it?

**Comment by moritzheiber** [comment]
Oh, I shouldn’t have replied to this while still half asleep, my apologies. Let me dig into it.

**Comment by moritzheiber** [comment]
So, your output isn't really specific about which `ruby` binary within the image you're using but I'm guessing you're referencing `/usr/local/bin/ruby`? The `ruby` binary that's built using this repository lives under `/opt/ruby` i.e. `/opt/ruby/bin/ruby` and it's linked against `libjemalloc.so.2` on `linux/arm64`:

```console
# ldd /opt/ruby/bin/ruby 
	libruby.so.3.2 => /opt/ruby/lib/libruby.so.3.2 (0x0000005502849000)
	libz.so.1 => /lib/aarch64-linux-gnu/libz.so.1 (0x0000005502e95000)
	librt.so.1 => /lib/aarch64-linux-gnu/librt.so.1 (0x0000005502ebf000)
	libjemalloc.so.2 => /usr/lib/aarch64-linux-gnu/libjemalloc.so.2 (0x0000005502ed7000)
	libgmp.so.10 => /usr/lib/aarch64-linux-gnu/libgmp.so.10 (0x0000005502ff1000)
	libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000005503079000)
	libcrypt.so.1 => /lib/aarch64-linux-gnu/libcrypt.so.1 (0x000000550308d000)
	libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x00000055030d8000)
	libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000005503183000)
	libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x00000055031b4000)
	/lib/ld-linux-aarch64.so.1 (0x0000005500000000)
	libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000005503328000)
	libstdc++.so.6 => /usr/lib/aarch64-linux-gnu/libstdc++.so.6 (0x000000550334c000)
```

The usual case here is to either use the image as a "builder instance" (akin to what [the `mastodon` image is doing](https://github.com/mastodon/mastodon/blob/main/Dockerfile#L5-L11)) or just import the image as a layer and then [`COPY` the interpreter into your image](https://github.com/mastodon/mastodon/blob/main/Dockerfile#L51-L56) to get rid of all all the other cruft that's in the original Debian `ruby` image.

In both instances you have to set `PATH` correctly (and probably `GEM_HOME`/`GEM_PATH` if you aren't using a bundle).

This image is explicitly not meant as a runtime image. Maybe I should clarify this in the `README`?

**Comment by jonbuda** [comment]
Got it! yeah it took me awhile to track down how to confirm jemalloc is being loaded. We also didn't intended to use it as a runtime image, but we have jemalloc running now and it is quite an improvement. thanks for clearing things up!

**Comment by moritzheiber** [comment]
Great. Happy to help!

**Comment by imtiazwazir** [comment]
@jonbuda - can you please share Dockerfile, having the same issue.
